server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/team2/ {
        proxy_pass http://k8s-msaservices-7d023f0bb9-676035063.ap-northeast-2.elb.amazonaws.com/api/team2/;
    }
    
    location /team2 {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    
    location /assets/ {
        alias /usr/share/nginx/html/assets/;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}
