export const constant = {
  SIREN: "siren",
  EDIT: "edit",
  DELETE: "delete",
  MALE: "남자",
  FEMALE: "여자",
  BREAKFAST: "BREAKFAST",
  LUNCH:"LUNCH",
  DINNER: "DINNER",
  SNACK: "snack",
  PLUS: "plus",
  MINUS: "minus",
  ALL: "ALL",
  LIKE: "LIKE",
  COMMENT: "COMMENT",
  MY: "MY",
}