export const constant = {
  SIREN: "siren",
  EDIT: "edit",
  THUMB: "thumb",
  DELETE: "delete",
  MALE: "남자",
  FEMALE: "여자",
  BREAKFAST: "BREAKFAST",
  LUNCH:"LUNCH",
  DINNER: "DINNER",
  SNACK: "snack",
  PLUS: "plus",
  MINUS: "minus",
  ALL: "ALL",
  LIKE: "LIKE",
  COMMENT: "COMMENT",
  MY: "MY",
  CARB: "탄수화물",
  PROTEIN: "단백질",
  FAT: "지방",
  DAY: "일일",
  WEEK: "주간",
  LINEAR: "선형",
  STICK: "막대",
}