export const string = {
  WELCOME: "명식당에 오신걸 환영합니다",
  USE: "이용하기",
  WRITE: "글 작성",
  SAVE: "저장하기",
  SAVEANDCLOSE: "저장하고 닫기",
  ADD: "추가하기",
  SELECT: "사진선택",
  COMPLETE: "작성완료",
  EDITCOMPLETE: "수정완료",
  CANCEL: "취소하기",
  EDIT: "수정",
  BLOCK: "차단",
  DELETE: "삭제",
  T_EDIT: "글 수정",
  T_DIET: "식단 추가",
  PHOTOEDIT: "사진 변경",
  CALORIE: "총 섭취 칼로리",
  M_CALORIE: "kcal",
  CARBOHYDRATE: "탄수화물",
  PROTEIN: "단백질",
  PROVINCE: "지방",
  MORNING: "아침",
  LUNCH: "점심",
  DINNER: "저녁",
  SNACK:"간식",
  GRAM: "gram",
  NUMBER: "개수",
  TITLE: "제목",
  MEAL: "학식 정보 불러오는 중...",
  WAIT: "잠시만 기다려주세요",
  ALL: "전체",
  LIKE: "좋아요 많은 순",
  COMMENT: "댓글 많은 순",
  MY: "내글만 보기",
  PH_TITLE: "제목을 입력해주세요.",
  CONTENT: "글 내용",
  PH_CONTENT: "글 내용을 입력해주세요.",
  PH_REPLY: "댓글을 입력해주세요",
  PH_SEARCH : "음식을 검색해보세요",

  BLANK: "공유된 식단이 없습니다.",
  BLANK_CONTENT: " 제일 먼저 글을 작성해보세요!",

  NONAME: "익명",

  TP_NOTITLE: "제목을 입력해주세요",
  TP_NOCONTENT: "내용을 입력해주세요",
  TP_NOIMAGE: "이미지를 업로드 해주세요",
  TP_BLOCK : "게시글이 차단되었습니다",

  SA_BLOCK : "차단시, 해당 글은 목록에 노출되지 않으며, 다시 해제가 불가능합니다",
  SA_DELETE: "게시글을 삭제 하시겠습니까?",


}