export const string = {
  WELCOME: "명식당에 오신걸 환영합니다",
  USE: "이용하기",
  WRITE: "글 작성",
  SAVE: "저장하기",
  SAVEANDCLOSE: "저장하고 닫기",
  ADD: "추가하기",
  SELECT: "사진선택",
  COMPLETE: "작성완료",
  EDITCOMPLETE: "수정완료",
  EDIT: "수정",
  DELETE: "삭제",
  T_EDIT: "글 수정",
  T_DIET: "식단 추가",
  PHOTOEDIT: "사진 변경",
  CALORIE: "총 섭취 칼로리",
  M_CALORIE: "kcal",
  CARBOHYDRATE: "탄수화물",
  PROTEIN: "단백질",
  PROVINCE: "지방",
  MORNING: "아침",
  LUNCH: "점심",
  DINNER: "저녁",
  SNACK:"간식",
  GRAM: "gram",
  NUMBER: "개수",

  TITLE: "제목",
  PH_TITLE: "제목을 입력해주세요.",
  CONTENT: "글 내용",
  PH_CONTENT: "글 내용을 입력해주세요.",
  PH_REPLY: "댓글을 입력해주세요",
  PH_SEARCH : "음식을 검색해보세요",
  BLANK: "공유된 식단이 없습니다.",
  BLANK_CONTENT: " 제일 먼저 글을 작성해보세요!",

  NONAME: "익명",

  TP_NOTITLE: "제목을 입력해주세요",
  TP_NOCONTENT: "내용을 입력해주세요",
  TP_NOIMAGE: "이미지를 업로드 해주세요",


}